apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-reminder-service
  namespace: production
  labels:
    app: prod-reminder-service
spec:
  selector:
    matchLabels:
      app: prod-reminder-service
  replicas: 2
  template:
    metadata:
      labels:
        app: prod-reminder-service
    spec:
      containers:
        - name: prod-reminder-service
          image: adisakshya/reminder-service:1.0.0-prod
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: prod-reminder-db-secrets
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: prod-reminder-db-secrets
                  key: name
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prod-reminder-db-secrets
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: prod-reminder-db-secrets
                  key: user
            - name: EVENT_TOPIC_ARN
              valueFrom:
                secretKeyRef:
                  name: prod-sns-topics-secrets
                  key: event_topic
