apiVersion: v1
kind: Service
metadata:
  name: dev-reminder-service
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: reminder-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
