---
# Hosts
all:
  hosts:
    # Localhost
    localhost:
      ansible_connection: local
      ansible_user: ansible
      ansible_host: 127.0.0.1

    # Local Minikube cluster
    minikube:
      ansible_connection: local
      ansible_user: minikube
      ansible_host: 192.168.56.100
    
    # AWS EKS Cluster
    k8sCluster:
      ansible_connection: local
      ansible_user: ansible
      ansible_host: 192.168.56.100
...
